services:
    qbus_wrapper_relation.data_container.content:
        class: Qbus\WrapperRelationBundle\DataContainer\Content
        arguments:
            - "@request_stack"
            - "@database_connection"
            - "@contao.framework"
        public: true
